#!/bin/sh

# Note: “local” is non-POSIX.

set -o errexit -o nounset

move_or_concatenate() {
	local state=~/.local/state/"$1" src from

	for src in .cache .state
	do
		from=~/"$src/$1"
		if ! [ -f "$from" ]
		then >&2 echo "[info] already migrated: $from"
		else
			>&2 echo "[info] migrating: $from"
			cat "$from" >>"$state"
			rm "$from"
		fi
	done
}

move_or_concatenate irb/history
move_or_concatenate pry/history
move_or_concatenate less/history
move_or_concatenate nodejs/repl_history
move_or_concatenate zsh/history

for src in .cache .state
do
	from=~/"$src"/vim/info vim_state=~/.local/state/vim/info
	if ! [ -f "${from}" ]
	then >&2 echo "[info] already migrated: $from"
	elif [ -f "${vim_state}" ]
	then >&2 echo '[error] Vim file needs to be manually migrated!'; exit 1
	else mv -v "${from}" "${vim_state}"
	fi
done
